language: ruby
rvm:
- 2.2.2

bundler_args: "--without development production"

before_install:
  - gem update --system
  - gem --version


script:
  - bundle exec rake db:drop db:create db:migrate
  - bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: OrZrWMEgSjABISW2zoJEcC65F0wvEfvjv/cfT/9rEcVSnvbn8rx2ap1iU74Wg3s7X1CjBckhH9uhYj2ZwOTqmhN/P8m9Oc+xQGjBeqar4xzZNILiyGWwl6VS/1AHoKk5D/k2E8fKg0uTrePxmIilravCpe8pwT1eud5Fp2cc3wM=
  app: shrouded-basin-1455
  on:
    branch: master
    repo: Olivia-tou/TraRe
  run:
    - "rake db:migrate"

notifications:
  slack: chubachi-pt-2015:MylvLlE5HOwVIZKXYYcrSjAn
